on:
    pull_request:
      branches:
        - main
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup Go
          uses: actions/setup-go@v5

        - name: Run Unit Tests
          run: go test -short -coverprofile cover.out ./...